# Generated by Django 4.2.5 on 2023-09-30 18:44

import pathlib

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "cities",
            },
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PurePosixPath("route_points/audio/%Y/%m/%d"),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PurePosixPath("route/images/%Y/%m/%d"),
                    ),
                ),
                ("duration", models.TimeField(default="01:00:00")),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("historical", "historical"),
                            ("artistic", "artistic"),
                        ],
                        default="historical",
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routes.city",
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routes.hero",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                ("short_description", models.TextField(blank=True)),
                ("google_maps_url", models.URLField(max_length=255)),
                ("order", models.PositiveSmallIntegerField()),
                ("description", models.TextField(blank=True)),
                ("hero_story", models.TextField(blank=True)),
                ("hero_quote", models.TextField(blank=True)),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PurePosixPath("route_points/images/%Y/%m/%d"),
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PurePosixPath("route_points/audio/%Y/%m/%d"),
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_points",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("route", "order")},
            },
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PurePosixPath("route_points/audio/%Y/%m/%d"),
                    ),
                ),
                ("image_description", models.TextField(blank=True)),
                (
                    "route_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="routes.routepoint",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("route_point", "order")},
            },
        ),
    ]
