# Generated by Django 4.2.5 on 2023-09-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                ("short_description", models.TextField()),
                ("google_maps_url", models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "basepoint_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="routes.basepoint",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
                (
                    "main_image",
                    models.ImageField(upload_to="route_points/images/%Y/%m/%d"),
                ),
                ("audio", models.FileField(upload_to="route_points/audio/%Y/%m/%d")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="routes.route"
                    ),
                ),
            ],
            bases=("routes.basepoint",),
        ),
    ]
