# Generated by Django 4.2.5 on 2023-09-30 16:58

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PurePosixPath("route_points/audio/%Y/%m/%d"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="route",
            name="duration",
            field=models.TimeField(default="01:00:00"),
        ),
        migrations.AddField(
            model_name="route",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath("route/images/%Y/%m/%d"),
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="route_type",
            field=models.CharField(
                choices=[("historical", "historical"), ("artistic", "artistic")],
                default="historical",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="basepoint",
            name="short_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="route",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath("route_points/audio/%Y/%m/%d"),
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath("route_points/images/%Y/%m/%d"),
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_points",
                to="routes.route",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routepoint",
            unique_together={("route", "order")},
        ),
        migrations.AddField(
            model_name="route",
            name="city",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="routes.city"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="hero",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="routes.hero",
            ),
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("text", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=pathlib.PurePosixPath("route_points/audio/%Y/%m/%d"),
                    ),
                ),
                ("image_description", models.TextField(blank=True)),
                (
                    "route_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paragraphs",
                        to="routes.routepoint",
                    ),
                ),
            ],
            options={
                "unique_together": {("route_point", "order")},
            },
        ),
    ]
