# Generated by Django 4.2.5 on 2023-09-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0002_city_hero_route_duration_route_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="paragraph",
            options={"ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="routepoint",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="routepoint",
            name="hero_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="routepoint",
            name="hero_story",
            field=models.TextField(blank=True),
        ),
    ]
