# Generated by Django 4.2.5 on 2023-10-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0003_alter_hero_image_alter_paragraph_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="comics_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
