# Generated by Django 4.2.5 on 2023-10-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routes", "0004_route_comics_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routepoint",
            name="google_maps_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="main_image",
            field=models.ImageField(
                blank=True, max_length=1000, null=True, upload_to=""
            ),
        ),
    ]
